### ISSUE TITLE
Call to noInterrupts()

### ISSUE THREAD

**Issue by fluidblue** [micromouseonline/BasicEncoder#3]
Hello,

first of all thank you for the library.

I just saw the code, and there are some calls to `noInterrupts()`.
According to the [docs](https://www.arduino.cc/reference/en/language/functions/interrupts/nointerrupts/), after a call to `noInterrupts()`, `interrupts()` must be called for interrupts to be enabled again.
Is it intentional that you leave out the calls to `interrupts()` or is it an error?

**Comment by micromouseonline** [comment]
Hi

Thank you for taking the time to comment.

Good question - I should have documented the usage.

Where interrupts are disabled, I first save the status register. Then, after the critical code, the status register is restored and the Interrupt Enable flag will have the value that was there before the suspension of interrupts. Thus I preserve state as much as possible

This is a safer approach because library code may have been called while interrupts are disabled for some other reason. To then re-enable the interrupts could be disastrous. 

These lines do the job

```C
    uint8_t sreg = SREG; // save the interrupt enable state
    noInterrupts();
    // what ever must not get interrupted
    SREG = sreg;    // state now restored
```

A more generic but equivalent technique is to use the macros in `<util/atomic.h>`. The method from that makes it a little more difficult to forget to restore the flag state.

You can read more here 
https://www.nongnu.org/avr-libc/user-manual/group__util__atomic.html
https://groups.google.com/a/arduino.cc/g/developers/c/cmu0Qy32zxY?pli=1
https://blog.oddbit.com/post/2019-02-01-atomicblock-magic-in-avrlibc/

**Comment by fluidblue** [comment]
OK, thanks for clarifying.
I think adding the comments to the library code would improve the readability.

From my side, this ticket can be closed.

**Comment by micromouseonline** [comment]
I will do that.
